### ISSUE TITLE
ci: can we configure pre-commit CI (ruff linting, prevent commit to `main`, etc)?

### ISSUE THREAD

**Issue by bobleesj** [ophusgroup/quantem#76]
### Problem

My understanding is that we run `ruff` via a separate GitHub Actions CI. 

### Proposed solution

Since we have `.pre-commit-config-yaml` provided in the repo, could we pre-commit via GitHub Actions like below?

<img width="451" alt="Image" src="https://github.com/user-attachments/assets/ae904eaf-4bfa-4c5c-b5a1-fe87eff495a9" />

Ref:

https://github.com/apps/pre-commit-ci

**Comment by bobleesj** [comment]
Due to the nature of open-source, anyone can simply fork and make a contribution as small as fixing typos, etc. and we do want to encourage that. However, we also want to ensure consistency in our codebase via - ruff, flake8, PEP8, PEP256, free of spelling error, etc via pre-commit, beyond preventing us from committing to `main` which the current CI does.

```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  # prettier - multi formatter for .json, .yml, and .md files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@^3.2.4"
  # docformatter - PEP 257 compliant docstring formatter
  - repo: https://github.com/s-weigand/docformatter
    rev: 5757c5190d95e5449f102ace83df92e7d3b06c6c
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
```

So, I'd argue that Pre-commit CI is the one that helps on the "formatting" and fail while we have other GitHub Actions for "testing" as we currently do.
