### ISSUE TITLE
ci: add Python 3.13 in `uv-pytests.yml`

### ISSUE THREAD

**Issue by bobleesj** [ophusgroup/quantem#79]
### Problem

At the moment, seems like the CI supports Py3.11 and 3.12. Since Py3.13 is stable, I've also tried adding Py3.13 and seems to work:

![Image](https://github.com/user-attachments/assets/59660e6e-c512-4495-a980-63d505bac62d)

Ref: https://github.com/bobleesj/quantem/pull/1

### Proposed solution

If there is no strong reason not to, add `"3.13"` below in `uv-pytests.yml`

```yml
  uv-pytests:
    name: python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
```

@gvarnavi happy to make a PR
